// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FormStyles$MyBlog from "./FormStyles.bs.js";

function InputField(Props) {
  var inputId = Props.inputId;
  var value = Props.value;
  var disabled = Props.disabled;
  var onChange = Props.onChange;
  var onBlur = Props.onBlur;
  var result = Props.result;
  var label = Props.label;
  var match = Props.placeholder;
  var placeholder = match !== undefined ? match : "";
  var match$1 = Props.type_;
  var type_ = match$1 !== undefined ? match$1 : "text";
  var tmp;
  if (result !== undefined) {
    var match$2 = result;
    tmp = match$2.tag ? React.createElement("div", {
            className: "help is-danger"
          }, match$2[0]) : null;
  } else {
    tmp = null;
  }
  return React.createElement("div", {
              className: "field is-horizontal"
            }, React.createElement("div", {
                  className: "field-label is-normal"
                }, React.createElement("label", {
                      className: "label"
                    }, label)), React.createElement("div", {
                  className: "field-body"
                }, React.createElement("div", {
                      className: "field"
                    }, React.createElement("input", {
                          className: FormStyles$MyBlog.inputFieldStyles(result),
                          id: inputId,
                          disabled: disabled,
                          placeholder: placeholder,
                          type: type_,
                          value: value,
                          onBlur: onBlur,
                          onChange: onChange
                        }), tmp)));
}

var make = InputField;

var $$default = InputField;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
