// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function $$Notification(Props) {
  var status = Props.status;
  var successMessage = Props.successMessage;
  var errorMessage = Props.errorMessage;
  if (typeof status === "number") {
    if (status === /* Editing */0) {
      return null;
    } else {
      return React.createElement("div", {
                  className: "notification is-success"
                }, successMessage);
    }
  } else if (status.tag) {
    return React.createElement("div", {
                className: "notification is-danger"
              }, errorMessage);
  } else {
    return null;
  }
}

var make = $$Notification;

export {
  make ,
  
}
/* react Not a pure module */
