// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Head from "next/head";
import * as Footer$MyBlog from "./Footer.bs.js";
import * as Navbar$MyBlog from "./navbar/Navbar.bs.js";
import * as UserProvider$MyBlog from "../user/UserProvider.bs.js";

((require('bulma')));

Css.$$global("p", /* :: */[
      Css.marginBottom(Css.px(20)),
      /* [] */0
    ]);

function reducer(param, action) {
  if (action) {
    return {
            user: /* Authenticated */[action[0]]
          };
  } else {
    return {
            user: /* Guest */0
          };
  }
}

function Page(Props) {
  var children = Props.children;
  var match = React.useReducer(reducer, {
        user: /* Guest */0
      });
  return React.createElement(UserProvider$MyBlog.make, UserProvider$MyBlog.makeProps(/* tuple */[
                  match[0].user,
                  match[1]
                ], null, /* () */0), React.createElement(Head.default, {
                  children: null
                }, React.createElement("meta", {
                      content: "width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover",
                      name: "viewport"
                    }), React.createElement("title", undefined, "Man Vs Code")), React.createElement(Navbar$MyBlog.make, { }), children, React.createElement(Footer$MyBlog.make, { }));
}

var make = Page;

export {
  reducer ,
  make ,
  
}
/*  Not a pure module */
