// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function initValue_001(param) {
  return /* () */0;
}

var initValue = /* tuple */[
  /* Guest */0,
  initValue_001
];

var context = React.createContext(initValue);

function useUser(param) {
  return React.useContext(context);
}

function handleStateChange(authstate, dispatchUserAction) {
  switch (authstate) {
    case "signIn" :
        return Curry._1(dispatchUserAction, /* UserLoggedOut */1);
    case "signedIn" :
        return Curry._1(dispatchUserAction, /* UserLoggedIn */0);
    default:
      return /* () */0;
  }
}

export {
  initValue ,
  context ,
  useUser ,
  handleStateChange ,
  
}
/* context Not a pure module */
