// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function initValue_001(param) {
  return /* () */0;
}

var initValue = /* tuple */[
  /* Guest */0,
  initValue_001
];

var context = React.createContext(initValue);

function useUser(param) {
  return React.useContext(context);
}

export {
  initValue ,
  context ,
  useUser ,
  
}
/* context Not a pure module */
