// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function Goodbye(Props) {
  return React.createElement("div", undefined, "Goodbye");
}

var make = Goodbye;

var $$default = Goodbye;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
