// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function Hello(Props) {
  return React.createElement("div", undefined, "Hello Eugene");
}

var make = Hello;

var $$default = Hello;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
