// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Link from "next/link";
import * as NavbarStyles$MyBlog from "./NavbarStyles.bs.js";
import * as SigninButton$MyBlog from "./SigninButton.bs.js";

function Navbar(Props) {
  var match = React.useReducer((function (state, action) {
          return {
                  menuIsActive: !state.menuIsActive
                };
        }), {
        menuIsActive: false
      });
  var dispatch = match[1];
  var state = match[0];
  return React.createElement("div", {
              className: "hero-head"
            }, React.createElement("nav", {
                  className: NavbarStyles$MyBlog.topnavStyles,
                  id: "topnav"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: NavbarStyles$MyBlog.navbarBrand
                        }, React.createElement(Link.default, {
                              href: "/",
                              children: React.createElement("a", {
                                    className: NavbarStyles$MyBlog.subtitle
                                  }, "MANvsCODE")
                            }), React.createElement("span", {
                              className: NavbarStyles$MyBlog.navbarBurger(state.menuIsActive),
                              onClick: (function (_event) {
                                  return Curry._1(dispatch, /* ToggleMenu */0);
                                })
                            }, React.createElement("span", undefined), React.createElement("span", undefined), React.createElement("span", undefined))), React.createElement("div", {
                          className: NavbarStyles$MyBlog.navbarMenu(state.menuIsActive),
                          id: "navbarMenu"
                        }, React.createElement("div", {
                              className: "navbar-end"
                            }, React.createElement("div", {
                                  className: NavbarStyles$MyBlog.navbarItem
                                }, React.createElement(Link.default, {
                                      href: "/about",
                                      children: React.createElement("a", undefined, "About")
                                    })), React.createElement("div", {
                                  className: NavbarStyles$MyBlog.navbarItem
                                }, React.createElement(Link.default, {
                                      href: "/contact",
                                      children: React.createElement("a", undefined, "contact")
                                    })), React.createElement(SigninButton$MyBlog.make, { }))))));
}

var make = Navbar;

export {
  make ,
  
}
/* react Not a pure module */
