// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

function getFieldStateStyle(fieldState) {
  if (fieldState !== undefined) {
    var match = fieldState;
    if (match.tag) {
      return "is-danger";
    } else if (match[0]) {
      return "";
    } else {
      return "is-success";
    }
  } else {
    return "";
  }
}

function inputFieldStyles(fieldState) {
  return Css.merge(/* :: */[
              "input",
              /* :: */[
                getFieldStateStyle(fieldState),
                /* [] */0
              ]
            ]);
}

function textareaFieldStyles(fieldState) {
  return Css.merge(/* :: */[
              "textarea",
              /* :: */[
                getFieldStateStyle(fieldState),
                /* [] */0
              ]
            ]);
}

export {
  getFieldStateStyle ,
  inputFieldStyles ,
  textareaFieldStyles ,
  
}
/* Css Not a pure module */
