// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactFontawesome from "@fortawesome/react-fontawesome";

function SubmitButton(Props) {
  var status = Props.status;
  var reset = Props.reset;
  var tmp;
  var exit = 0;
  if (typeof status === "number") {
    if (status === /* Editing */0) {
      exit = 1;
    } else {
      tmp = React.createElement("button", {
            className: "button is-link is-success",
            disabled: true
          }, React.createElement(ReactFontawesome.FontAwesomeIcon, {
                icon: "check"
              }), React.createElement("span", undefined, " Saved"));
    }
  } else if (status.tag) {
    exit = 1;
  } else {
    tmp = React.createElement("button", {
          className: "button is-link is-loading"
        }, React.createElement("span", undefined, "Submitting"));
  }
  if (exit === 1) {
    tmp = React.createElement("button", {
          className: "button is-link"
        }, React.createElement("span", undefined, "Submit"));
  }
  return React.createElement("div", {
              className: "field is-grouped is-pulled-right"
            }, React.createElement("div", {
                  className: "control"
                }, tmp), React.createElement("div", {
                  className: "control"
                }, React.createElement("button", {
                      className: "button is-link is-light",
                      onClick: (function (param) {
                          return Curry._1(reset, /* () */0);
                        })
                    }, "Cancel")));
}

var make = SubmitButton;

var $$default = SubmitButton;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
