// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function modalStyles(modalState) {
  return Css.merge(/* :: */[
              modalState ? "is-active" : "",
              /* :: */[
                "modal",
                /* [] */0
              ]
            ]);
}

function Modal(Props) {
  var isActive = Props.isActive;
  var closeModal = Props.closeModal;
  var children = Props.children;
  return React.createElement("div", {
              className: modalStyles(isActive)
            }, React.createElement("div", {
                  className: "modal-background"
                }), React.createElement("div", {
                  className: "modal-content"
                }, children), React.createElement("button", {
                  className: "modal-close is-large",
                  onClick: (function (_event) {
                      return Curry._1(closeModal, /* () */0);
                    })
                }));
}

var make = Modal;

var $$default = Modal;

export {
  modalStyles ,
  make ,
  $$default ,
  $$default as default,
  
}
/* Css Not a pure module */
