// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Tag(Props) {
  var text = Props.text;
  return React.createElement("a", {
              href: "#"
            }, React.createElement("span", {
                  className: "tag is-info is-rounded"
                }, "#" + text));
}

var make = Tag;

var $$default = Tag;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
