// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as UserContext$MyBlog from "./UserContext.bs.js";

var make = UserContext$MyBlog.context.Provider;

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

export {
  make ,
  makeProps ,
  
}
/* make Not a pure module */
