// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Modal$MyBlog from "../Modal.bs.js";
import * as AwsAmplifyReact from "aws-amplify-react";
import * as UserContext$MyBlog from "../../user/UserContext.bs.js";

function SigninModal(Props) {
  var isActive = Props.isActive;
  var closeModal = Props.closeModal;
  var match = Props.isSignUpModal;
  var isSignUpModal = match !== undefined ? match : false;
  var match$1 = UserContext$MyBlog.useUser(/* () */0);
  var dispatchUserAction = match$1[1];
  return React.createElement(Modal$MyBlog.make, {
              isActive: isActive,
              closeModal: closeModal,
              children: isSignUpModal ? React.createElement(AwsAmplifyReact.Authenticator, {
                      onStateChange: (function (authState, authData) {
                          return UserContext$MyBlog.handleStateChange(authState, dispatchUserAction);
                        })
                    }) : React.createElement(AwsAmplifyReact.Authenticator, {
                      hideDefault: true,
                      onStateChange: (function (authState, authData) {
                          return UserContext$MyBlog.handleStateChange(authState, dispatchUserAction);
                        }),
                      children: React.createElement(AwsAmplifyReact.SignIn, { })
                    })
            });
}

var make = SigninModal;

export {
  make ,
  
}
/* react Not a pure module */
