// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://m27sdqjzh5aldhn75i6ykuxrt4.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-h6siqak64ndnljx2or7pzdwjji",
    "aws_cognito_identity_pool_id": "ap-southeast-2:c2538fb4-bb45-4f4e-ab99-c1fbb3ba256b",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_pcNi1cVvz",
    "aws_user_pools_web_client_id": "19jqdoj571ue5lrnssa6sp2rl2",
    "oauth": {}
};


export default awsmobile;
