// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as AwsAmplify from "aws-amplify";

var signOut = AwsAmplify.Auth.signOut;

function SignoutButton(Props) {
  var closeModal = Props.closeModal;
  return React.createElement("div", {
              className: "buttons"
            }, React.createElement("a", {
                  className: "button is-warning",
                  onClick: (function (param) {
                      AwsAmplify.Auth.signOut();
                      return Curry._1(closeModal, /* () */0);
                    })
                }, React.createElement("strong", undefined, "Sign out")));
}

var make = SignoutButton;

var $$default = SignoutButton;

export {
  signOut ,
  make ,
  $$default ,
  $$default as default,
  
}
/* signOut Not a pure module */
