// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as SigninModal$MyBlog from "./SigninModal.bs.js";
import * as UserContext$MyBlog from "../../user/UserContext.bs.js";
import * as SignoutButton$MyBlog from "./SignoutButton.bs.js";

var linkStyle = Css.selector("a", /* :: */[
      Css.color(Css.rgb(130, 130, 130)),
      /* [] */0
    ]);

var linkHover = Css.selector("a:hover", /* :: */[
      Css.borderBottom(Css.px(1), Css.solid, Css.white),
      /* [] */0
    ]);

var navbarItem = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.background(Css.rgb(0, 107, 198)),
            /* :: */[
              Css.color(Css.rgb(130, 130, 130)),
              /* :: */[
                linkStyle,
                /* :: */[
                  linkHover,
                  /* [] */0
                ]
              ]
            ]
          ]),
      /* :: */[
        "navbar-item",
        /* [] */0
      ]
    ]);

function reducer(state, action) {
  switch (action) {
    case 0 : 
        return /* record */[
                /* signInModalIsActive */!state[/* signInModalIsActive */0],
                /* signUpModalIsActive */false
              ];
    case 1 : 
        return /* record */[
                /* signInModalIsActive */false,
                /* signUpModalIsActive */!state[/* signUpModalIsActive */1]
              ];
    case 2 : 
        return /* record */[
                /* signInModalIsActive */false,
                /* signUpModalIsActive */false
              ];
    
  }
}

function SigninButton(Props) {
  var match = UserContext$MyBlog.useUser(/* () */0);
  var match$1 = React.useReducer(reducer, /* record */[
        /* signInModalIsActive */false,
        /* signUpModalIsActive */false
      ]);
  var dispatchModalAction = match$1[1];
  var state = match$1[0];
  return React.createElement("div", {
              className: navbarItem
            }, match[0] ? React.createElement(SignoutButton$MyBlog.make, {
                    closeModal: (function (param) {
                        return Curry._1(dispatchModalAction, /* CloseModal */2);
                      })
                  }) : React.createElement("div", {
                    className: "buttons"
                  }, React.createElement("a", {
                        className: "button is-warning",
                        onClick: (function (_event) {
                            return Curry._1(dispatchModalAction, /* ToggleSignUpModal */1);
                          })
                      }, React.createElement("strong", undefined, "Sign up")), React.createElement("a", {
                        className: "button is-light",
                        onClick: (function (_event) {
                            return Curry._1(dispatchModalAction, /* ToggleSignInModal */0);
                          })
                      }, "Log in"), React.createElement(SigninModal$MyBlog.make, {
                        isActive: state[/* signInModalIsActive */0],
                        closeModal: (function (param) {
                            return Curry._1(dispatchModalAction, /* CloseModal */2);
                          })
                      }), React.createElement(SigninModal$MyBlog.make, {
                        isActive: state[/* signUpModalIsActive */1],
                        closeModal: (function (param) {
                            return Curry._1(dispatchModalAction, /* CloseModal */2);
                          }),
                        isSignUpModal: true
                      })));
}

var make = SigninButton;

var $$default = SigninButton;

export {
  linkStyle ,
  linkHover ,
  navbarItem ,
  reducer ,
  make ,
  $$default ,
  $$default as default,
  
}
/* linkStyle Not a pure module */
