// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Section$MyBlog from "../src/components/layout/Section.bs.js";

function str(prim) {
  return prim;
}

function make(param) {
  return React.createElement(Section$MyBlog.make, {
              title: "About",
              subtitle: "This is the about page",
              children: React.createElement("p", undefined, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id. Vehicula ipsum a arcu cursus vitae congue. Libero enim sed faucibus turpis in eu mi bibendum. Lectus mauris ultrices eros in. Tincidunt lobortis feugiat vivamus at augue eget. Porta non pulvinar neque laoreet suspendisse interdum consectetur. Pellentesque diam volutpat commodo sed egestas egestas fringilla. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Neque viverra justo nec ultrices dui sapien eget mi. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper.")
            });
}

var $$default = make;

export {
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
