// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Hero$MyBlog from "../src/components/layout/Hero.bs.js";
import * as Posts$MyBlog from "./posts.bs.js";

function Index(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Hero$MyBlog.make, {
                  title: "Man vs Code",
                  subtitle: "A blog for the ages"
                }), React.createElement(Posts$MyBlog.make, { }));
}

var make = Index;

var $$default = Index;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
