// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Section$MyBlog from "../src/components/layout/Section.bs.js";
import * as PostForm$MyBlog from "../src/components/post/postform/PostForm.bs.js";

function Createpost(Props) {
  return React.createElement(Section$MyBlog.make, {
              title: "Create Post",
              subtitle: "",
              children: React.createElement(PostForm$MyBlog.make, {
                    authorId: "1234"
                  })
            });
}

var make = Createpost;

var $$default = Createpost;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
